// <auto-generated />
using Explordamweb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Explordamweb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Explordamweb.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameID");

                    b.Property<int?>("OrderID");

                    b.Property<int>("Quantity");

                    b.HasKey("CartLineID");

                    b.HasIndex("GameID");

                    b.HasIndex("OrderID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("Explordamweb.Models.Games", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutText");

                    b.Property<string>("Background");

                    b.Property<string>("Category");

                    b.Property<bool>("CategoryCoop");

                    b.Property<bool>("CategoryMMO");

                    b.Property<bool>("CategoryMultiplayer");

                    b.Property<bool>("CategorySinglePlayer");

                    b.Property<bool>("CategoryVRSupport");

                    b.Property<bool>("ControllerSupport");

                    b.Property<int>("DLCCount");

                    b.Property<string>("DetailedDescrip");

                    b.Property<string>("Genre")
                        .IsRequired();

                    b.Property<bool>("GenreIsAction");

                    b.Property<bool>("GenreIsAdventure");

                    b.Property<bool>("GenreIsCasual");

                    b.Property<bool>("GenreIsIndie");

                    b.Property<bool>("GenreIsMassivelyMultiplayer");

                    b.Property<bool>("GenreIsNonGame");

                    b.Property<bool>("GenreIsRPG");

                    b.Property<bool>("GenreIsRacing");

                    b.Property<bool>("GenreIsSimulation");

                    b.Property<bool>("GenreIsSports");

                    b.Property<bool>("GenreIsStrategy");

                    b.Property<string>("HeaderImage");

                    b.Property<bool>("IsFree");

                    b.Property<string>("LegalNotice");

                    b.Property<string>("LinuxMinReqsText");

                    b.Property<string>("LinuxRecReqsText");

                    b.Property<string>("MacMinReqsText");

                    b.Property<string>("MacRecReqsText");

                    b.Property<int>("Metacritic");

                    b.Property<string>("PCMinReqsText");

                    b.Property<string>("PCRecReqsText");

                    b.Property<string>("Platform");

                    b.Property<bool>("PlatformLinux");

                    b.Property<bool>("PlatformMac");

                    b.Property<bool>("PlatformWindows");

                    b.Property<string>("PriceCurrency");

                    b.Property<decimal>("PriceFinal");

                    b.Property<decimal>("PriceInitial");

                    b.Property<string>("QueryName")
                        .IsRequired();

                    b.Property<int>("RecommendationCount");

                    b.Property<string>("ReleaseDate");

                    b.Property<int>("RequiredAge");

                    b.Property<string>("Reviews");

                    b.Property<string>("ShortDescrip");

                    b.Property<string>("SupportEmail");

                    b.Property<string>("SupportURL");

                    b.Property<string>("SupportedLanguages");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Explordamweb.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Orderdate");

                    b.Property<bool>("Shipped");

                    b.Property<string>("Surname");

                    b.Property<string>("UserID");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Explordamweb.Models.Wishitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("GameGenre");

                    b.Property<int>("GameId");

                    b.Property<string>("GameImage");

                    b.Property<string>("GameName");

                    b.Property<decimal>("GamePrice");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("Explordamweb.Models.CartLine", b =>
                {
                    b.HasOne("Explordamweb.Models.Games", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.HasOne("Explordamweb.Models.Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");
                });
#pragma warning restore 612, 618
        }
    }
}
